
spring:
  application:
    name: MSTxFleet-DBS-Cassandra
  cassandra:
    keyspace-name: mykeyspace
    contact-points: cassandra
    schema-action: create_if_not_exists
    create-keyspace: true
  cloud:
    discovery:
      enabled: true


server:
  port: 0

