
spring:
  docker:
    compose:
      file: ./MSTxFleet-DBS-Cassandra/compose.yaml
  application:
    name: MSTxFleet-DBS-Cassandra
  cassandra:
    keyspace-name: mykeyspace
    contact-points: cassandra
    schema-action: create_if_not_exists
    create-keyspace: true


server:
  port: 0

